version: "2.4"
services:
  base:
    build: .
    volumes:
      - ".:/app"
      - "~/.config/gcloud:/root/.config/gcloud"

  terminal:
    extends:
      service: base
    command: bash
    environment:
      IMDB_DATASET_URL: "https://datasets.imdbws.com"
      GCP_PROJECT: "imdb-dataset"
