Description: IMDB Dataset Project Stack

Parameters:
  Image:
    Type: String
  EcsCluster: 
    Default: jonathans-cluster
    Type: String
  ServiceName:
    Default: 'imdb-dataset'
    Type: String
  ImdbDatasetUrl:
    Type: String
    Default: 'https://datasets.imdbws.com'
  GcpProject:
    Type: String
    Default: 'imdb-dataset'
  KmsEncryptedGcpCredentials:
    Type: String
    Default: 'AQICAHhTt858E/r+o8Av2YmGo18ueU9PgrwNYkGEmpegj/FkTQH/w7F+nhEeGHrW1HQu6daMAAAJizCCCYcGCSqGSIb3DQEHBqCCCXgwggl0AgEAMIIJbQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwBQgRdRJUuaQywqnkCARCAggk+IpDyKFf7VBUR2QQXEYjuoIvI7FkUilHSUmPWo5e9KNyPeccfqtN7NAUeBL5YvrhyyiFM4SPPIDMaPub0uf3PeRfzhSdLTCLVxmHPirZ0FttbI2d7osggClwaFeRmvlD4oClzdaTE9zbrGRgv5nLNkzn2fAvSZ6hSuFzIbjk0aF4px8O5AyDOGAe8mxo4MH9W1ZgEjaMwQcOtQtCQV+W+t8Eu6iU+TU2hhHOc++Eopa9c3XNWnqqs96uOxOyeK0kC8CvfEEqSvNXUPIULmhH+crBribN37rz2L+7VkcN5jp0NHx62nIShj8d3kSUuujqZl722D3ySi9PXudZqm+HtH2gHx6+++FxupoxuahqrnC8wSAPIUgKNel+WGfo2hfSrNfCZRloE5JcwpIyefXxOVA+vIVNst7rROnKVFLeqUp7aMzFd+d+6wYeTyGiYYSwOdOM5PY+DcZ1LEm0UXe9mR3NL8OuMhsIgqiAGV6vg6bcMOJvhA8Jel/dDQJpXnHkaeMh26e2uHFJhaWTBTwNDsWbG4bZDWUYD6g2bAae9OabeeFgS+Nq4V5eFGMC3U/xeSVxPqEYUDA7IvvuKuGzH0+V68inQAY+ML964na3O08VP+k7DpNL+hsKW03E84b4uOhYsfl3a4KuVu2ZWNVFmEnt0sjCSG5l/nEq2hSHyEUQWlJfMAs35452/FSj7iRj6LkdX0z5rkhMnps7Ct+fa16PDEotI/yVNqV9vtCds+K76IRW0GXQyR67+IOlHhMlPqRe1YwfrBedBxUfhfHKxZvwx+sQ55JP4LYZuMwmny43uKyiDrQwBx8c8R6ABAGdSjxi0yPzxPNEtqRMfG7yn6UWX0i1jXKXJMSTvDgWNyK9TLIVhJc4Usht8yd/CnZN4U8NrxZQYfJZBlYJ4PDagRJYJ4PDfFucNI6IUD1dCrVDDctqBieuaEPSdWW9l+PQwKrjuBM9L8+bY4Rzzh5n/KKdTJzvyrXuiGxsnA+ShAdLEL+/mOBytkfY6tqY7u9YkLBDCiEzH6FqZZIVaH5tjTiuz7yVqztwjOsZ2b8UmSC8qUIWbz1kx0kKz+b6/J5Lp+eCMKAq62Xa+G6WbNJMw/s7RzqDyLITB+rOXbqnMikdSm50qyP1okf4L8pmYBmu7CeF8eWIjSzN5/qBkuwu5NqQaylKWBhjPW79EKBW6ahAICRXqU8RJQHml7sogvvMCRmB5ajyaKt/5MFiZ+BCY6Y7pH44TtMPHySwtkJCHrRIsmEe1KDNMZPzR9HCwTJrFTImWNpxcE/Bvgx9W9ol86qYPRhVRiENlT6PW3+ZA6FEV+H3TyDKTgmclaIVpPdk/mlb0VikzSFn6tqQaI5Wwn4kg5IWPbDosL9EtS6PvQur01lgYhREhRiEJsrOGIKXeI2mSolirWEuAIy+XLDoQyB8Pf/gO1av+toqoNloVfSSgsIfN78XnYXw0YVeKdXcustscWH1ZtXI/bImNH6KyL8BcQYWgD0N4Ip6NcB1pRHto5M8Wj6AC72XQ+UgzEnjGLTljxIhDVbhHSbAglYkekDQpTw7P3ZwBWIGGBDi8i3ADSSKQ9/nlEPeG2MQ+3INSfgRHCwiIJgJs3spJplHrN5IKnqMZGipDPiB5amc8Nh/XoJRb0OCRAQ06TUwfv5idvTmyuuzs6RwdB9qjckyissCsheYVqEo8O9RosaYoWcxcksq7PNyR6q3EdGNYkSfjZk+I5Oj1HSHVJn80ESs24ZAOAvg3xh+A2d5I6IWbTsA8XqqSHoy8PDKpR912naYZYmJJeqYQURMr9jXhjWSGWVl40sy+r4aNy5rq5JnRsY0rYicwxPoGThuNpO9FsuVK7uKJv+Vqt4fNaRu7vnBepV7bcucXlqLT0qB4etCqYqN8EF1FyfNHYO70sSLo7MvdclP7k1TUSy+srfC8dsoIDdiuy1stv2zoQMQWHSz5drpJJBbB1HqyDBMrHmbVuDdDWuz34SlJmbbtj8hQjX0oQ5vz9dt1qbS39MmInNavIssRIkakTLIXN0as4VSMZnqf9VWeQ4hE4wQ20GGC5JztA/W2kBpZm4tlIbK7I3FCDHxoXMAe4Mrc2gSk0A2gL6TZOTCWa130dlCG02Yuxgn0Y84qLnDSEvICXZSxJn4HsWczjvj8X7y8RVyhnzpW5yQ028uCMtl5kn4mk0Ycn+ovrp84b/LRUac/y/8zg3aYVPVnNuGyaAmSmIv2oZtDduGa2dtM29IijcVa37FXnYV8uUl4RoyX3ZUKxYiBVxNKnU1/M3Ddb6UhQ2eoDngZzD229NJDxRWSweuJkdKAg4SsgLo9pr1UrpDJUfOVeXQKlv+PZh3W3LU3ORcuKudNXKsyes45sXA5qA63FUZ9todv9ODSJZyt+YnE+RuSNo52KR/75DwVC51vhXAAFF96uwieQLt/P2au7lMnnIxNeg8aYMSQTW7+PgTuxH/0wL41VqPD9z7cXVmkIF8Ds4SOs1NyXB43tO43YqjxeJqu/MI3Lv2Qos0Zmv3nf+VDvD/yOHAJwPhZ2ElHJ1lNi0IP+JL6LLXVlln9MQ56AO1xBayh7b6BCFfqyVEeq5k1bhn3uw9pvWUzhE7po/HmvIX6iIzom9DhkWpfVJRfrpqG/h5ExG4ZJJQ6t5QndPOxS4T9R7UFjctLwzBwxx7FmYBGa+3IB1i7/PXMYcs05+DpTg5kyy5wMrmgBddsS1x5YrT61DvIG1n77+nnLMohwznBl0vtKjvbQHbrqZ/nRDiRzeeZyP2cWIIgE9cWSbpVYCRVCHh1nZLz5b2EZffu4nn1qHCwDfaEVEf4e0CMWYMSSsy2GiZqhNalzkJUZ1gbobZI0WyalWuE5f7XfmT4faS56IdcPfdp0JtLt1+KP0wCnikIabtHKBd0sM4ZNDmTOFnLsIOXB+otNtmNh00NAx9Cb1ok9/9hbh4pMb6h0dP6iyZ0pM/kEkNXpDDFXAta2yUA+5y55lwy8LpViqMtpyzkJ93GbOElhusKDVLU709Opfro4P7feO0xUPuaHgH+rrn9lyPO4/I8P+NtyoNuBG3Z7WFl5dZ0RHsOVVmAmBBvtpPbEPd8BmR+agsdb+fRwwNc35+1W/CUKYuxIdTl9YFqtwBPXeP5zn49rUAfNG+X4rs='
  ExecutionCronSchedule:
    Type: String
    Default: 'cron(0 0 ? 1/1 THU#1 *)'
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Default: 'subnet-05d8e77ce04a1394f'
  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Default: 'sg-001e6dcfe1ab6b85c'

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties:
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 0.5GB
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: imdb-dataset
          Image: !Ref Image
          Environment:
            - Name: IMDB_DATASET_URL
              Value: !Ref ImdbDatasetUrl
            - Name: GCP_PROJECT
              Value: !Ref GcpProject
            - Name: KMS_ENCRYPTED_GCP_CREDENTIALS
              Value: !Ref KmsEncryptedGcpCredentials
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs

  ScheduleExecutionRule:
    Type: AWS::Events::Rule
    Properties:
      Description: !Sub 'Trigger ${ServiceName} according to the specified schedule'
      ScheduleExpression: !Ref ExecutionCronSchedule
      State: ENABLED
      Targets:
      - Id: !Sub '${ServiceName}-Fargate-Task'
        Arn: !Sub 'arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${EcsCluster}'
        RoleArn: !GetAtt ScheduleTaskRole.Arn
        EcsParameters:
          TaskDefinitionArn: !Ref TaskDefinition
          TaskCount: 1
          LaunchType: 'FARGATE'
          PlatformVersion: 'LATEST'
          NetworkConfiguration:
            AwsVpcConfiguration:
              AssignPublicIp: ENABLED
              SecurityGroups: !Ref SecurityGroups
              Subnets: !Ref Subnets

  ScheduleTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: AllowEcsAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: RunTask
                Effect: Allow
                Action:
                  - ecs:RunTask
                Resource:
                  - !Ref TaskDefinition
              - Sid: AllowListingTasks
                Effect: Allow
                Action:
                  - ecs:DescribeTasks
                Resource:
                  - "*"

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinition]]
      RetentionInDays: 7
