Description: IMDB Dataset Project Stack

Parameters:
  Image:
    Type: String
  EcsCluster: 
    Default: jonathans-cluster
    Type: String
  ServiceName:
    Default: 'imdb-dataset'
    Type: String
  ImdbDatasetUrl:
    Type: String
    Default: 'https://datasets.imdbws.com'
  GcpProject:
    Type: String
    Default: 'imdb-dataset'

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties:
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 0.5GB
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: imdb-dataset
          Image: !Ref Image
          Environment:
            - Name: IMDB_DATASET_URL
              Value: !Ref ImdbDatasetUrl
            - Name: GCP_PROJECT
              Value: !Ref GcpProject
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinition]]
      RetentionInDays: 7
